# 🎨 Frontend Deployment для Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anonymeme-frontend
  namespace: anonymeme
  labels:
    app: anonymeme-frontend
    component: web
    version: v1.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: anonymeme-frontend
  template:
    metadata:
      labels:
        app: anonymeme-frontend
        component: web
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/api/metrics"
    spec:
      serviceAccountName: anonymeme-frontend
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: frontend
        image: ghcr.io/anonymeme/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: anonymeme-config
              key: api-url
        - name: NEXT_PUBLIC_WS_URL
          valueFrom:
            configMapKeyRef:
              name: anonymeme-config
              key: websocket-url
        - name: NEXT_PUBLIC_SOLANA_RPC_URL
          valueFrom:
            configMapKeyRef:
              name: anonymeme-config
              key: solana-rpc-url
        - name: NEXT_PUBLIC_CONTRACT_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: anonymeme-config
              key: contract-address
        - name: NEXT_PUBLIC_ENVIRONMENT
          value: "production"
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: cache
          mountPath: /app/.next/cache
      volumes:
      - name: cache
        emptyDir: {}
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: anonymeme-frontend-service
  namespace: anonymeme
  labels:
    app: anonymeme-frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/api/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: anonymeme-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: anonymeme-frontend
  namespace: anonymeme
  labels:
    app: anonymeme-frontend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: anonymeme-frontend-hpa
  namespace: anonymeme
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: anonymeme-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30