# 🔌 WebSocket Deployment для Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anonymeme-websocket
  namespace: anonymeme
  labels:
    app: anonymeme-websocket
    component: realtime
    version: v1.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: anonymeme-websocket
  template:
    metadata:
      labels:
        app: anonymeme-websocket
        component: realtime
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: anonymeme-websocket
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: websocket
        image: ghcr.io/anonymeme/websocket:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: websocket
          protocol: TCP
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: anonymeme-secrets
              key: redis-url
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: anonymeme-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: anonymeme-secrets
              key: secret-key
        - name: SOLANA_RPC_URL
          valueFrom:
            configMapKeyRef:
              name: anonymeme-config
              key: solana-rpc-url
        - name: CONTRACT_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: anonymeme-config
              key: contract-address
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "warning"
        - name: PYTHONPATH
          value: "/app"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: anonymeme-websocket-service
  namespace: anonymeme
  labels:
    app: anonymeme-websocket
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: websocket
  selector:
    app: anonymeme-websocket
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: anonymeme-websocket
  namespace: anonymeme
  labels:
    app: anonymeme-websocket
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: anonymeme-websocket-hpa
  namespace: anonymeme
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: anonymeme-websocket
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30